name: MacroDensity CI

on:
  pull_request:
    branches:
      - development(calysta)
      - main
  push:
    branches:
      - development(calysta)
      - main

jobs:

#   qa:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pre-commit/action@v2.0.0

  test:
    #needs: qa
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm wheel
        pip install -r requirements.txt
        pip install pytest
        pip install -e .
    
    - name: Check package versions
      run: |
        pip show -V pytest
        pip show -V ase
    
    - name: Run tests
      run: pytest tests/unit_tests.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
    
