name: MacroDensity CI

on:
  pull_request:
    branches:
      - master
      - development(calysta)
  push:
    branches:
      - master
      - development(calysta)

jobs:

#   qa:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pre-commit/action@v2.0.0

  test:
    #needs: qa
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest,]

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm wheel
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install pytest-mpl
        pip install -e .

    - name: Check package versions
      run: |
        pip show -V pytest
        pip show -V ase
        pip show -V matplotlib

    - name: Run tests
      run: pytest --cov=macrodensity --mpl tests/unit_tests.py --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
        files: ./coverage.xml
